
/* #include "version.h" when build_info.xml generates it */

/* These are the values for Unix */
#define DAEMON_NAME 			"tagEventord"
#define DEFAULT_LOCK_FILE_DIR	"/var/run"
#define DEFAULT_COMMAND_DIR		"/etc/tagEventor/scripts"
#define VERSION_STRING			"0.1.0" /* combination of VERSION_CODE, BUILD_TIME, VERSION_NUMBER generated by build_info.xml" */
